title: ForecastWeather
email: jp.rizzi@wanadoo.fr
description: >- # this means to ignore newlines until "baseurl:"
  The Forecast Weather app allows you to check weather data for a route,
  particularly wind speed and direction. Forecast Weather can also provide 
  recommendations for devices compatible with Apple Intelligence.
baseurl: "/forecastweather" # the subpath of your site, e.g. /blog
theme: just-the-docs

url: https://yeti23.github.io

#aux_links:
#  Template Repository: https://github.com/just-the-docs/just-the-docs-template
